const IMAGES ={
    headerLogo: require('./logo.png'),
    sliderOneImg: require('./section1sliderImg1.jpg'),
    sliderOneImg2: require('./section1sliderImg2.jpg'),
    sectionTwoImg1: require('./section2Img1.png'),
    sectionTwoImg2: require('./section2Img2.png'),
    sectionTwoImg3: require('./section2Img3.png'),
    sectionTwoImg4: require('./section2Img4.png'),
    sectionTwoImg5: require('./section2Img5.png'),
    sectionthreeImg1: require('./section3Img1.jpg'),
    sectionthreeImg2: require('./section3Img2.jpg'),
    sectionthreeImg3: require('./section3Img3.jpg'),
    sectionFourImg1: require('./section4SliImg1.jpg'),
    sectionFourImg2: require('./section4SliImg2.jpg'),
    sectionFourImg3: require('./section4SliImg3.jpg'),
    sectionFourImg4: require('./section4SliImg4.jpg'),
    sectionFourImg5: require('./section4SliImg5.jpg'),
    sectionFourImg6: require('./section4SliImg6.jpg'),
    sectionFiveImg1: require('./section5Img1.png'),
    sectionFiveImg2: require('./section5Img2.png'),
    sectionFiveImg3: require('./section5Img3.png'),
    sectionFiveImg4: require('./section5Img4.png'),
    sectionFiveImg5: require('./section5Img5.png'),
    headerLiImg1: require('./headerImg1.png'),
    headerLiImg2: require('./headerImg2.png'),
    headerLiImg3: require('./headerImg3.png'),
    headerLiImg4: require('./headerImg4.png'),
    headerLiImg5: require('./headerImg5.png'),
    headerLiImg6: require('./headerImg6.png'),
    headerLiImg7: require('./headerImg7.png'),
    headerLiImg8: require('./headerImgH.png'),
    headerLiImg9: require('./headerImgI.png'),
    headerLiImg10: require('./contact-icon.png'),
    singleImg1: require('./birbank-cards.png'),
    singleImg2: require('./cash.png'),
    singleImg3: require('./whatsapp_logo.png'),
   
}

export default IMAGES;