
export default {
    translation:{
        "Homepage": "Ana SƏHİFƏ",
        "aboutAs":"Haqqımızda",
        "contactUs": "BİZİMLƏ əlaqə",
        "furnitureList":"mebel SİYAHISI",
        "changeTheLanguage":"DİLİ DƏYİŞDİRİN",
        "bed":"Yataq",
        "guest":"Qonaq",
        "young":"Uşaq və Gənc",
        "table":"Masa və stullar",
        "californiya":"Californiya yataq dəsti",
        "kataniya":"Kataniya yataq dəsti",
        "miracle":"Miracle yataq dəsti",
        "safir":"Safir yataq dəsti",
        "richmond":"Richmont yataq dəsti",
        "verona":"Verona yataq dəsti",
        "fenomen":"Fenomen yataq dəsti",
        "tiffany":"Tiffany yataq dəsti",
        "alyans":"Alyans cream yataq dəsti",
        "melen":"Melen yataq dəsti",
        "nirvana":"Nirvana yataq dəsti",
        "toskana":"Toskana yataq dəsti",
        "toskanaQ":"Toskana qonaq dəsti",
        "vivaldiQ":"Vivaldi TV stend",
        "arizonaQ":"Arizona TV altı 2400",
        "ricmondQ":"Ricmond asma dolab",
        "miracleQ":"Miracle qonaq dəsti",
        "miracleQG":"Miracle qonaq komod - güzgü",
        "eyforiyaQ":"Eyforiya qonaq dəsti",
        "floridaQ":"Florida qonaq dəsti",
        "gloriyaQ":"Gloria qonaq dəsti",
        "melenQ":"Melen qonaq dəsti",
        "nirvanaQ":"Nirvana qonaq dəsti",
        "ricmondQ1":"Richmond qonaq dəsti",
        "tiffanyQ":"Tiffony qonaq dəsti",
        "arizonaQ1":"Arizona qonaq dəsti",
        "vivaldiQ1":"Vivaldi qonaq dəsti",
        "tiffanyG":"Tiffany gənc dəsti",
        "angelG":"Angel gənc dəsti",
        "londonG":"London uşaq dəsti",
        "kelebekG":"Kelebek uşaq dəsti",
        "enjoyG":"Enjoy uşaq dəsti",
        "oscarG":"Oscar mavi uşaq dəsti",
        "oscarG1":"Oscar uşaq dəsti",
        "sunriseG":"Sunrise gənc dəsti",
        "gloriyaG":"Gloriya gənc dəsti",
        "babyG":"Baby uşaq beşik",
        "nirvanaM":"Nirvana masa mexanizm",
        "toskanaM":"Toskana masa",
        "arizonaM":"Arizona masa",
        "vivaldiM":"Vivaldi masa mexanizm",
        "stM":"ST 7779",
        "stmoonM":"ST Moon",
        "streoM":"ST Reo",
        "jurnalM":"Jurnal Masa",
        "jurnalM1":"Jurnal Masa",
        "jurnalM2":"Jurnal Masa",
        "jurnalM3":"Jurnal Masa",
        "kreditF":"Kredİt şərtlərİ",
        "legalF":"HÜQUQİ XƏBƏRDARLIQ",
        "aboutF":"Haqqımızda",
        "securyF":"MAĞAZALARIMIZ",
        "contacktF":"bİzİmlə əlaqə",
        "storesF":"Məxfİlİk sİyasətİ",
        "musteriF":"Müştərİ Xİdmətlərİ",
        "musteriF1":"Müştəri xidməti",
        "musteriMeqaleF1":"Fəaliyyət göstərdiyimiz hər bir ölkədə aktiv müştəri xidməti xətləri və satışdan sonrakı xidmət qurmuşuq. Belə ki, yaşadığı ölkədən asılı olmayaraq, Mebel mebeli almış hər bir müştərimiz sonrakı periodlarda yarana biləcək istənilən problem, nasazlıq barəsində bizə müraciət edə bilər. Hər bir sorğu, istər zəmanət müddəti çərçivəsində, istərsə də zəmanət müddətindən sonra diqqətlə araşdırlır və müvafiq olaraq həll edilir.",
        "zemanet1":"5 illik zəmanət!",
        "zemanet2":"Mebel istehsalı prosesinin hər bir mərhələsində: xammal alışından başlayaraq məhsulların paketlənməsinə qədər bütün proseslər ciddi keyfiyyət nəzarətindən keçir. Belə yanaşmamızın nəticəsidir ki, bütün mebel məhsullarımıza 5 illik zəmanət veririk. Bununla belə, istənilən mebel modelimizi almaqla Siz ömür boyu etibar edə biləcəyiniz keyfiyyət əldə edirsiniz. Çünki, biz hər bir mebel modelimizə sevgi və nəvazişlə yanaşırıq. Sizin üçün istehsal edirik. Sizin xidmətinizdəyik!",
        "chatdirilma1":"24 saat ərzində çatdırılma və quraşdırma!",
        "chatdirilma2":"Mebel sizə pulsuz çatdırma və quraşdırma xidməti təqdim edir. İstənilən brend mağazamızda, istənilən miqdarda mebel alın və 24 saat ərzində aldığınız mebel evinizdə olacaqdır. Xüsusi təlim keçmiş montaj qrupumuz operativ şəkildə və peşəkar səviyyədə mebelinizi ən qısa müddət ərzində quraşdıracaqdır.",
        "newF":"YENİ MƏHSULLAR",
        "unvanF":"Bakı, AZ 1065, B. Bağırova küç. 15B",
        "shopByColHome":"ÖZ KOLLEKSİYANI YARAT",
        "yataqHome":"YATAQ MEBELİ",
        "qonaqHome":"QONAQ MEBELİ",
        "rockingSec3Hom":"SALLANAN KRESLO",
        "youngSec3Hom":"KOLON İŞIQ",
        "tableSec3Hom":"SERVANT MASASI",
        "WievSec3Hom":"DAHA ÇOX",
        "blogSec4Hom":"BLOQDAN",
        "haqqimizdaHaq":"Haqqımızda",
        "loremHaq":"Lorem Ipsum sadəcə çap və çap sənayesinin saxta mətnidir. Lorem Ipsum, 1500-cü illərdən bəri sənayenin standart dummy mətni olmuşdur, naməlum printer bir tipli qalereya götürdü və bir növ nümunə kitabı hazırlamaq üçün onu qarışdırdı. O, təkcə beş əsr ərzində deyil, həm də elektron çapa sıçrayışdan sonra, mahiyyətcə dəyişməz olaraq sağ qaldı.",
        "li1Haq":"İstifadəçi razılaşması",
        "li2Haq":"Keyfiyyət",
        "li3Haq":"Kredit və geri qaytarma şərtləri",
        "li4Haq":"Onlayn alış qaydaları",
        "buttonHaq":"Bizimlə əlaqə",
        "adContact":"Adınız",
        "movzuContact":"Mövzu",
        "mesajContact":"Mesajınız(İstəyə görə)",
        "buttonContact":"Göndər",
        "unvanContact":"Ünvan",
        "BasOfisunvanContact":"Baş ofisin ünvanı: Bakı, AZ 1065, B. Bağırova küç. 15B",
        "countryContact":"Azərbaycan",
        "TelContact":"Telefon",
        "workTimeContact":"Bazar ertəsi - Cümə 8:00 - 18:00 ",
        "sebetWis":"Səbətə at",
        "arzuWis":"Arzu siyahısı",
        "hesabWis":"Hesab",
        "anbardaWis":"Anbarda",
        "bitibWis":"Bitib",
        "sebetCart":"Səbət",
        "emptyCart":"Səbətinizdə heç bir məhsul yoxdur!",
        "buttonCart":"Sifarişi tamamla",
        "button1Cart":"Davam et",
        "qiymet":"Qiymətə görə sıralayın",
        "qiymetAraligi":"QİYMƏT ARALIĞI",
        "search":"Məhsul axtarın",
        "deyisF":"MEBELİN DƏYİŞDİRİLMƏSİ VƏ YA QAYTARILMASI AŞAĞIDAKI HALLARDA TƏMİN EDİLİR",
        "yanlisF":"Müştəri mebelin sifarişi zamanı onun ölçüsü, modeli və dizayn seçimində yanlışlığa yol verərsə MEBEL şirkəti mebelin qaytarılmasından və ya dəyişdirilməsindən imtina etmək hüququna malikdir.",
        "mudafieF":"İstehlakçıların hüquqlarının müdafiəsi haqqında Azərbaycan Respublikasının Qanununun 15-ci maddəsinə görə İstehlakçı tərəfindən əldə edilmiş lazımı keyfiyyətli mal istifadə olunmayıbsa plombu, yarlığı, həmçinin mal və yaxud kassa qəbzi və ya ona mal ilə birlikdə verilmiş digər sənədləri saxlanılıbsa, bu hallarda o (14 gün ərzində) qaytarıla və dəyişdirilə bilər. Buhalda bununla bağlı daşınma və sənədləşmə xərcləri müştəri, digər hallarda isə şirkət tərəfindən qarşılanır.",
        "sertF":'Kredit şərtləri',
        "sert1F":'Rəsmi gəliri olan şəxslər şəxsiyyət vəsiqəsi ilə, rəsmi gəliri olmayan şəxslər isə zaminlə 12 və 18 aylıq faizsiz kredit imkanından yararlana bilərlər. *Rəsmi iş yeriniz vardırsa (6 aydan az olmayaraq) (Rəsmi iş yeri olmayan şəxslərdən zamin tələb oluna bilər), *Vöen ödəyicisinizsə (1 ildən az olmayaraq), *Təqaüdçüsünüzsə (68 yaşa qədər) Online kredit üçün müraciət edə bilərsiniz.',
        "xidmetF":'Xidmət haqqı',
        "komissiyaF":'0% komisiyya',
        "prosesF":'Kredit prosesi',
        "proses1F":'Sifariş qeydə alındıqdan sonra, kredit mütəxəssisləri əlaqə saxlayaraq sizə kredit ayrıla bilinib-bilinməməsi və aylıq ödənişlər barədə ətraflı məlumat təqdim edəcək. Kredit ayrıla bilindiyi halda , yalnız siz təsdiqlədikdən sonra sifariş aktivləşəcək.',
        "odenisF":'Kredit ödənişi',
        "odenis1F":'Kredit ödənişinizi Milliön, hesab.az, kassam.az vasitəsilə edə bilərsiniz.',
        "mexfiF":'TOPLANAN MƏLUMATLAR',
        "mexfi1F":'Məxfilik siyasəti',
        "qeydiyyatF":'Qeydiyyat prosesi zamanı qeydiyyat formasında göstərilmiş tələb olunan digər məlumatlarla yanaşı tam adınız, telefon nömrəniz, elektron poçt ünvanınız və faktiki ünvanınızı əldə edə bilərik. Veb-saytdakı fəaliyyətiniz zamanı siz kredit/debit kartı və ya PayPal hesabınızdan istifadə edərək sifariş yerləşdirdikdə biz sizin əməliyyat məlumatlarınızı əldə edə bilirik. Eyni zamanda, İP ünvanınız, istifadə etdiyiniz əməliyyat sisteminiz və brauzer məlumatlarınızı da toplayırıq.',
        "topMelumatF":'TOPLANMIŞ MƏLUMATLARIN İSTİFADƏSİ',
        "topMelumat1F":'Biz sizin məlumatlarınızı aşağıdakı məqsədlərlə istifadə edə bilərik: Tələblərinizə cavab vermək məqsədilə xidmətlərimizi yaxşılaşdırmaq və təkmilləşdirmək üçün müştərilərimiz və onların tələbləri ilə daha yaxından tanış olmaq. Sizi daha yaxşı müştəri dəstəyi ilə təmin etmək. Sizinlə ünsiyyət qurmaq. Hesabınızla əlaqədar problemlərin aşkarı və aradan qaldırılması zamanı daşınma ilə bağlı sizi məlumatlandırmaq və ya yeni işlərimiz barədə məlumat əldə etməyinizə imkan yaratmaq',
        "tehlukesizlikF":'TƏHLÜKƏSİZLİK',
        "tehlukesizlik1F":'Siz sifariş yerləşdirərkən və məxfi məlumatlarınızı (kredit və ya debit kartındakı məlumatlar) təqdim edərkən onların təhlükəsizliyi və məxfiliyi bizim tərəfimizdən tamamilə təmin olunur. Nəzərinizə çatdırmaq istərdik ki, bütün şəxsi məlumatlar Secure Socket Layer (SSL) texnologiyası vasitəsilə ötürülür. Sizin kredit/debit kart nömrələriniz və şəxsi məlumatlarınız saxlanılmayacaq, satılmayacaq və ya hər hansı üçüncü tərəflə paylaşılmayacaq.',
        "COOKIESF":'COOKIES',
        "COOKIES1F":'Biz sizin şəxsi məlumatlarınızın toplanılması üçün cookies-dən istifadə etmirik. İstifadə edə biləcəyimiz yeganə cookies izləmə sessiyasının İD-ləri və istifadəçi rejimidir.',
        
    }
}

