
export default {
    translation:{
        "Homepage":"Home pages",
        "aboutAs":"about us",
        "furnitureList":"furniture list",
        "contactUs":"contact us",
        "changeTheLanguage":"change the language",
        "bed":"Bed",
        "guest":"Guest",
        "young":"Babay and Young",
        "table":"Table and chair",
        "californiya":"Californiya bedding",
        "kataniya":"Kataniya bedding",
        "miracle":"Miracle bedding",
        "safir":"Safir bedding",
        "richmond":"Richmond bedding",
        "verona":"Verona bedding",
        "fenomen":"Phenomenal bedding",
        "tiffany":"Tiffany bedding",
        "alyans":"Alliance crem bed set",
        "melen":"Melen bed sett",
        "nirvana":"Nirvana bedding",
        "toskana":"Tuscan bedding",
        "toskanaQ":"Tuscan guest suite",
        "vivaldiQ":"Vivaldi TV stand",
        "arizonaQ":"Arizona TV bottom 2400",
        "ricmondQ":"Richmond wardrobe",
        "miracleQ":"Miracle guest suite",
        "miracleQG":"Miracle guest dresser - mirror",
        "eyforiyaQ":"Euphoria guest suite",
        "floridaQ":"Florida guest suite",
        "gloriyaQ":"Gloria guest suite",
        "melenQ":"Melen guest suite",
        "nirvanaQ":"Nirvana guest suite",
        "ricmondQ1":"Richmond guest suite",
        "tiffanyQ":"Tiffany guest suite",
        "arizonaQ1":"Arizona guest suite",
        "vivaldiQ1":"Vivaldi guest suite",
        "tiffanyG":"Tiffany junior set",
        "angelG":"Angel young set",
        "londonG":"London children's set",
        "kelebekG":"Butterfly children's set",
        "enjoyG":"Enjoy children's set",
        "oscarG":"Oscar blue children's set",
        "oscarG1":"Oscar children's set",
        "sunriseG":"Sunrise junior set",
        "gloriyaG":"Gloria young set",
        "babyG":"Baby crib",
        "nirvanaM":"Nirvana table mechanism",
        "toskanaM":"Tuscan table",
        "arizonaM":"Arizona table",
        "vivaldiM":"Vivaldi table mechanism",
        "stM":"ST 7779",
        "stmoonM":"ST Moon",
        "streoM":"ST Reo",
        "jurnalM":"Magazine Table",
        "jurnalM1":"Magazine Table",
        "jurnalM2":"Magazine Table",
        "jurnalM3":"Magazine Table",
        "kreditF":"Credİt condİtİons",
        "legalF":"LEGAL NOTICE",
        "aboutF":"ABOUT AS",
        "securyF":"OUR SHOPS",
        "contacktF":"CONTACT AS",
        "storesF":"STORES",
        "musteriF":"Customer service",
        "musteriF1":"Customer service",
        "musteriMeqaleF1":"We have established active customer service lines and after-sales service in every country where we operate. So, regardless of the country where he lives, every customer who bought furniture can contact us about any problems or malfunctions that may arise in the following periods. Every inquiry, whether within the warranty period or after the warranty period, is carefully investigated and dealt with accordingly.",
        "zemanet1":"5 year warranty!",
        "zemanet2":"At each stage of the furniture production process: from the purchase of raw materials to the packaging of products, all processes undergo strict quality control. As a result of this approach, we provide a 5-year warranty on all our furniture products. However, by purchasing any of our furniture models, you get quality you can trust for a lifetime. Because we treat each of our furniture models with love and affection. We produce for you. We are at your service!",
        "chatdirilma1":"Delivery and installation within 24 hours!",
        "chatdirilma2":"Furniture provides you with free delivery and installation service. Buy any amount of furniture in our store of any brand and within 24 hours the furniture you bought will be at your home. Our specially trained installation team will promptly and professionally install your furniture in the shortest possible time.",
        "newF":"NEW PRODUCTS",
        "unvanF":"Baku, AZ 1065, B. Baghirova St. 15B",
        "shopByColHome":"SHOP BY COLLECTION",
        "yataqHome":"BEDDING FURNITURE",
        "qonaqHome":"LIVING ROOM FURNITURE",
        "rockingSec3Hom":"ROCKING CHAIR",
        "youngSec3Hom":"PENDANT LIGHT",
        "tableSec3Hom":"SIDEBOARD TABLE",
        "WievSec3Hom":"VIEW MORE",
        "blogSec4Hom":"FROM THE BLOG",
        "haqqimizdaHaq":"About AS",
        "loremHaq":"Lorem ipsum dolor, sit amet consectetur adipisicing elit.Ipsa corrupti recusandae harum. Rem consequuntur culpa sunt quisquam reiciendis dolores cum ad eveniet illum saepe recusandae, tempora rerum ducimus dignissimos facere.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni reiciendis, debitis consequuntur beatae aliquam natus.",
        "li1Haq":"User agreement",
        "li2Haq":"Quality",
        "li3Haq":"Credit and refund terms",
        "li4Haq":"Online purchase rules",
        "buttonHaq":"Contact us",
        "adContact":"Your name",
        "movzuContact":"Subject",
        "mesajContact":"Your message(By request)",
        "buttonContact":"Send",
        "unvanContact":"Address",
        "BasOfisunvanContact":"Head office address: Baku, AZ 1065, B. Baghirova str. 15B",
        "countryContact":"Azerbaijan",
        "TelContact":"Phone",
        "workTimeContact":"Monday - Friday 8:00 - 18:00",
        "sebetWis":"Add to cart",
        "arzuWis":"Wish list",
        "hesabWis":"Account",
        "anbardaWis":"In the warehouse",
        "bitibWis":"It's over",
        "sebetCart":"Basket",
        "emptyCart":"There are no products in your cart!",
        "buttonCart":"Complete the order",
        "button1Cart":"Continue",
        "qiymet":"Filter By Price",
        "qiymetAraligi":"PRİCE RANGE",
        "search":"Search product",
        "deyisF":"EXCHANGE OR REFUND OF FURNITURE IS PROVIDED IN THE FOLLOWING CASES",
        "yanlisF":"MEBEL company has the right to refuse to return or exchange the furniture if the customer makes a mistake in choosing the size, model and design of the furniture when ordering it.",
        "mudafieF":"According to Article 15 of the Law of the Republic of Azerbaijan on the Protection of Consumers' Rights, if the good quality goods purchased by the Consumer have not been used, and if the seal, label, as well as the goods or cash register receipt or other documents issued to him along with the goods have been kept, in such cases (within 14 days) can be returned and exchanged. In this case, the costs of transportation and documentation are borne by the customer, and in other cases by the company.",
        "sert":'Credit conditions',
        "sert1":'Persons with official income can take advantage of 12- and 18-month interest-free loans with an ID card, and those without official income with a guarantor. *You can apply for an online loan if you have an official job (not less than 6 months) (persons without an official job may require a guarantor), *if you are a tax payer (not less than 1 year), *retired (up to 68 years old).',
        "xidmet":'Price for the service',
        "komissiya":' 0% commission',
        "prosesF":'Credit process',
        "proses1F":'After the order is registered, the credit specialists will contact you and provide you with detailed information about the loan availability and monthly payments. If the credit can be allocated, the order will be activated only after your confirmation.',
        "odenisF":'Loan payment',
        "odenis1F":'You can make your loan payment through Milliön, hesb.az, kassam.az.',
        "mexfiF":'INFORMATION COLLECTED',
        "mexfi1F":'Məxfilik siyasəti',
        "qeydiyyatF":'During the registration process, we may obtain your full name, telephone number, email address and physical address, along with other required information provided on the registration form. When you place an order using your credit/debit card or PayPal account during your visit to the Website, we may receive your transaction information. At the same time, we also collect your IP address, the operating system you use and your browser information.',
        "topMelumatF":'USE OF COLLECTED INFORMATION',
        "topMelumat1F":'We may use your information for the following purposes: Getting to know our customers and their requirements better in order to improve and improve our services to meet your needs.To provide you with better customer support.To communicate with you. To notify you about shipping or to let you know about new things we do when we detect and fix problems with your account',
        "tehlukesizlikF":'SECURITY',
        "tehlukesizlik1F":'When you place an order and provide your confidential information (credit or debit card information), their security and privacy are fully guaranteed by us. We would like to inform you that all personal data is transmitted via Secure Socket Layer (SSL) technology. Your credit/debit card numbers and personal information will not be stored, sold or shared with any third party.',
        "COOKIESF":'COOKIES',
        "COOKIES1F":'We do not use cookies to collect your personal information. The only cookies we can use are tracking session IDs and user mode.',
    }
}

